# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Fabric', '~> 1.7.2'
pod 'Crashlytics', '~> 3.9.3'
pod 'Firebase/Database'

target 'NarouReader' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NarouReader

  target 'NarouReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NarouReader-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NarouReader-tvOS

  target 'NarouReader-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
